# feeder
feeder: feeder.feeder_STGCN.Feeder
test_feeder_args:
  - name: SPHERE-Sit
    data_path: ./data/Finetune/data_and_label_SPHERE-Sit.pkl
    time_process:
      overlength: downsampling_uniform_offset
      underlength: upsampling_fill_zero

# model
model: net.ST_GCN.CausalModel
model_args:
  in_channels: 3
  num_class: 2
  graph_args:
    layout: human36M
    strategy: uniform
model_nc: net.ST_GCN.NonCausalHead
model_nc_args:
  num_class: 2
