# feeder
feeder: feeder.feeder_SkateFormer.PretrainFeeder
train_feeder_args:
  - name: UMONS-TAICHI
    data_path: ./data/Pretrain/data_and_label_UMONS-TAICHI.pkl
    data_length: 256
    partition: True
    score_range:
      min: 0
      max: 10
    score_trend: True
    data_sampler: feeder.BatchSampler.SubjectBatchSampler
    batch_size: 1
  - name: MMFS
    data_path: ./data/Pretrain/data_and_label_MMFS.pkl
    data_length: 320
    partition: True
    score_range:
      min: 0
      max: 17.3
    score_trend: True
    data_sampler: feeder.BatchSampler.SubjectBatchSampler
    batch_size: 32
  - name: Rhythmic-Gymnastics
    data_path: ./data/Pretrain/data_and_label_Rhythmic-Gymnastics.pkl
    data_length: 2304
    partition: True
    score_range:
      min: 3.85
      max: 24
    score_trend: True
    data_sampler: SequentialSampler
    batch_size: 32
  - name: AGF-Olympics
    data_path: ./data/Pretrain/data_and_label_AGF-Olympics.pkl
    data_length: 3520
    partition: True
    score_range:
      min: 10.966
      max: 16.2
    score_trend: True
    data_sampler: SequentialSampler
    batch_size: 32
  - name: FineFS
    data_path: ./data/Pretrain/data_and_label_FineFS.pkl
    data_length: 320
    partition: True
    score_range:
      min: 0
      max: 21.21
    score_trend: True
    data_sampler: feeder.BatchSampler.SubjectBatchSampler
    batch_size: 32
  - name: UI-PRMD
    data_path: ./data/Pretrain/data_and_label_UI-PRMD.pkl
    data_length: 64
    partition: True
    score_range:
      min: 0
      max: 1
    score_trend: True
    data_sampler: feeder.BatchSampler.SubjectBatchSampler
    batch_size: 8
  - name: KIMORE
    data_path: ./data/Pretrain/data_and_label_KIMORE.pkl
    data_length: 64
    partition: True
    score_range:
      min: 0
      max: 50
    score_trend: True
    data_sampler: feeder.BatchSampler.SubjectBatchSampler
    batch_size: 16
  - name: Push-Up
    data_path: ./data/Pretrain/data_and_label_Push-Up.pkl
    data_length: 64
    partition: True
    score_range:
      min: 0
      max: 1
    score_trend: False
    data_sampler: SequentialSampler
    batch_size: 32
  - name: 3D-Yoga
    data_path: ./data/Pretrain/data_and_label_3D-Yoga.pkl
    data_length: 64
    partition: True
    score_range:
      min: 0
      max: 3
    score_trend: True
    data_sampler: feeder.BatchSampler.SubjectBatchSampler
    batch_size: 8
  - name: FMS
    data_path: ./data/Pretrain/data_and_label_FMS.pkl
    data_length: 128
    partition: True
    score_range:
      min: 0
      max: 3
    score_trend: True
    data_sampler: feeder.BatchSampler.SubjectBatchSampler
    batch_size: 8

# model
model: net.SkateFormer.SkateFormer_pretrain_
model_args:
  in_channels: 3
  num_class: 1
  num_points: 16
  num_people: 1
  kernel_size: 7
  num_heads: 32
  attn_drop: 0.5
  head_drop: 0.0
  rel: True
  drop_path: 0.2
  type_1_size: [ 4, 4 ]
  type_2_size: [ 4, 8 ]
  type_3_size: [ 4, 4 ]
  type_4_size: [ 4, 8 ]
  mlp_ratio: 4.0
  index_t: True
  sigmoid: True